#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Sep 13 18:02:14 2018

@author: deepak
"""

import requests
from bs4 import BeautifulSoup
page=requests.get("https://forecast.weather.gov/MapClick.php?lat=37.7772&lon=-122.4168#.W5pYpBThU8o")
print(page)        # return an object
print(page.status_code)     #200 sucessfully download     
soup=BeautifulSoup(page.content,"html.parser") #implicity need to define otherwissw it will take xmls
print(soup.prettify)
print(soup.title) 
# find all the href links
"""for i,link in enumerate(soup.find_all('a')):
    print(i,link.get("href"))"""
# find all list
"""for i,list in enumerate(soup.find_all('li')):
    print(i,list.text) """
"""print(type(soup.children))
for item in list(soup.children):
    print(type(item)) """
    
forecast=soup.find('ul',id="seven-day-forecast-list",class_="list-unstyled")
#print(forecast)
print(type(forecast))
#print(forecast.text)
#for i,li in enumerate(forecast):
 # print(i,li.text) 

seven_day = soup.find(id="seven-day-forecast")
forecast_items = seven_day.find_all(class_="tombstone-container")
print(type(forecast_items))
tonight = forecast_items[0]
friday=forecast_items[2]
print(friday.text)
print(tonight.text) #print(tonight) #print all tags
#print(tonight.pretiffy)  # print list with tags

news=soup.find('div',id="news-items")
#print(news.text) # only text will print
#print(news) # print text with tags